# Generated by Django 2.0.4 on 2018-04-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180424_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='_post_likes_+', to='posts.Post'),
        ),
    ]
